global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'one-heartbeat'
    static_configs:
      - targets: ['localhost:9090']
    file_sd_configs:
      - files:
          - './build/metrics/macse.prom'
    scrape_interval: 30s
    metrics_path: /metrics
